$ErrorActionPreference='Stop'
$deployRoot=Split-Path -Parent $PSScriptRoot
$module=Join-Path $deployRoot 'SafeReadPackageV2.psm1';$verify=Join-Path $deployRoot 'verify_saferead_microhost_bundle.ps1';$install=Join-Path $deployRoot 'install_saferead_microhost_bundle.ps1';$builder=Join-Path $deployRoot 'build_saferead_package_v2.ps1'
Import-Module $module -Force

function Write-JsonFile([string]$Path,$Value){[IO.File]::WriteAllText($Path,(ConvertTo-SafeReadCanonicalJson $Value),[Text.UTF8Encoding]::new($false))}
function Assert-ThrowsLike([scriptblock]$Action,[string]$Pattern){try{&$Action}catch{if($_.Exception.Message -like $Pattern){return};throw "Expected '$Pattern', got '$($_.Exception.Message)'."};throw "Expected '$Pattern', but action succeeded."}
function Get-TestFacts([string]$Year,[string]$Name='RevitOperator.SafeReadHost'){$expected=Get-SafeReadExpectedTarget $Year;[pscustomobject]@{Name=$Name;TargetFramework=$expected.TargetFrameworkAttribute;Platform='Amd64';Mvid=('00000000-0000-0000-0000-{0}' -f $Year.PadLeft(12,'0'));RevitApiReferenceVersion=('{0}.0.0.0' -f $expected.RevitApiMajor);AssemblyReferences=@()}}
function Add-TestAuthenticodeCertificateTable([string]$Path){
  $bytes=[IO.File]::ReadAllBytes($Path);if($bytes.Length -lt 256){throw 'Synthetic signing fixture is not a PE image.'}
  $pe=[BitConverter]::ToInt32($bytes,0x3c);if($pe -lt 0 -or $pe+24 -ge $bytes.Length -or [BitConverter]::ToUInt32($bytes,$pe) -ne 0x00004550){throw 'Synthetic signing fixture has an invalid PE header.'}
  $optional=$pe+24;$magic=[BitConverter]::ToUInt16($bytes,$optional);$directories=if($magic -eq 0x10b){$optional+96}elseif($magic -eq 0x20b){$optional+112}else{throw 'Synthetic signing fixture has an unsupported optional header.'}
  $security=$directories+(8*4);if($security+8 -gt $bytes.Length -or [BitConverter]::ToUInt32($bytes,$security) -ne 0 -or [BitConverter]::ToUInt32($bytes,$security+4) -ne 0){throw 'Synthetic signing fixture already has a certificate table.'}
  $certificateOffset=[int]([Math]::Ceiling($bytes.Length/8.0)*8);$signed=New-Object byte[] ($certificateOffset+16);[Array]::Copy($bytes,$signed,$bytes.Length)
  [BitConverter]::GetBytes([uint32]$certificateOffset).CopyTo($signed,$security);[BitConverter]::GetBytes([uint32]16).CopyTo($signed,$security+4)
  [BitConverter]::GetBytes([uint32]16).CopyTo($signed,$certificateOffset);[BitConverter]::GetBytes([uint16]0x0200).CopyTo($signed,$certificateOffset+4);[BitConverter]::GetBytes([uint16]0x0002).CopyTo($signed,$certificateOffset+6)
  [Text.Encoding]::ASCII.GetBytes('TESTCERT').CopyTo($signed,$certificateOffset+8);[IO.File]::WriteAllBytes($Path,$signed)
}
$signatureVerifier={param($Path)[pscustomobject]@{Status='Valid';Thumbprint='TESTSIGNER'}}
$assemblyInspector={param($Path,$Year,$Item)Get-TestFacts $Year ([IO.Path]::GetFileNameWithoutExtension($Path))}

function New-TestBundle([string]$Root,[string]$ReleaseId='safe-read-v2-a'){
  $templateSource=Resolve-Path (Join-Path $deployRoot '..\..\apps\revit-safe-read-host\addin\RevitOperator.SafeReadHost.addin.template')
  New-Item -ItemType Directory -Force -Path $Root|Out-Null;$targets=@();$tuples=@()
  foreach($year in '2023','2024','2025'){
    $expected=Get-SafeReadExpectedTarget $year;$targetRoot=Join-Path $Root "targets\$year";$payloadRoot=Join-Path $targetRoot 'payload';$manifestRoot=Join-Path $targetRoot 'manifest';New-Item -ItemType Directory -Force -Path $payloadRoot,$manifestRoot|Out-Null
    $items=@([ordered]@{fileName='RevitOperator.SafeReadHost.dll';role='host';revitApiBound=$true},[ordered]@{fileName='RevitOperator.SafeReadCertifiedExecution.dll';role='certified_executor';revitApiBound=$true})
    $payload=@()
    foreach($item in $items){$path=Join-Path $payloadRoot $item.fileName;[IO.File]::WriteAllText($path,"$year-$($item.role)",[Text.UTF8Encoding]::new($false));$facts=Get-TestFacts $year ([IO.Path]::GetFileNameWithoutExtension($item.fileName));$payload += [ordered]@{path="payload/$($item.fileName)";role=$item.role;revitApiBound=$item.revitApiBound;sha256=Get-SafeReadSha256 $path;sizeBytes=(Get-Item $path).Length;assembly=[ordered]@{name=$facts.Name;targetFramework=$facts.TargetFramework;platform=$facts.Platform;mvid=$facts.Mvid;revitApiReferenceVersion=$facts.RevitApiReferenceVersion;references=@()};provenance=$null}}
    $template=Join-Path $manifestRoot 'RevitOperator.SafeReadHost.addin.template';Copy-Item -LiteralPath $templateSource -Destination $template
    $api=[ordered]@{contentSha256=('sha256:'+($year[0].ToString()*64));mvid=('10000000-0000-0000-0000-{0}' -f $year.PadLeft(12,'0'));assemblyVersion=('{0}.0.0.0' -f $expected.RevitApiMajor)}
    $proofRoot=Join-Path $targetRoot 'proof';New-Item -ItemType Directory -Force -Path $proofRoot|Out-Null;$proofPath=Join-Path $proofRoot 'proof.receipt.json';$proofArtifacts=[ordered]@{};foreach($proofYear in '2023','2024','2025'){$proofExpected=Get-SafeReadExpectedTarget $proofYear;$proofArtifacts[$proofYear]=[ordered]@{fileName="RevitOperator.SafeReadCertifiedExecution.Revit$proofYear.dll";sha256=('d'*64);length=100;managedCodeSha256=('e'*64);assemblyIdentity='RevitOperator.SafeReadCertifiedExecution, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null';targetFramework=$proofExpected.TargetFrameworkAttribute;platform='x64'}};$proofReceipt=[ordered]@{schemaVersion=1;proofKind='revit-safe-read-certified-kernel/v1';mode='check';status='verified';certified=$true;manifestSha256=('c'*64);trustBoundary='test';compilerOptions=@('test');issues=@();observation=[ordered]@{};artifacts=$proofArtifacts};Write-JsonFile $proofPath $proofReceipt;$proofSha=Get-SafeReadSha256 $proofPath
    $executor=@($payload|Where-Object role -eq 'certified_executor')[0];$managed=('e'*64);$executor.provenance=[ordered]@{proofReceiptSha256=$proofSha;unsignedSha256=('sha256:'+('d'*64));managedCodeSha256=$managed}
    $runtime=[ordered]@{schema='revit-operator.safe-read-runtime-attestation.v1';state='active';issued_at_utc='2030-01-01T00:00:00.000Z';expires_at_utc='2030-01-01T00:05:00.000Z';route_id='safe_read.sheet_count.v1';route_contract_sha256='sha256:cc80c231ba289396516164cb0fdbc3c71779ac018e717085f07a544530e68874';policy_sha256='sha256:23692b21a7e728e9c1ce5eec9580dcec4f3ac7f25d3d95059899c680a17aad67';proof_sha256=$proofSha;executor_id='revit-operator.safe-read-host.v1';runtime_tuple=[ordered]@{host_content_sha256=$executor.sha256;host_mvid=$executor.assembly.mvid;revit_api_content_sha256=$api.contentSha256;revit_api_mvid=$api.mvid;revit_version=$year}}
    $runtimePath=Join-Path $payloadRoot 'safe_read_runtime_attestation.v1.json';Write-JsonFile $runtimePath $runtime;$runtimePin=Get-SafeReadSha256 $runtimePath;[IO.File]::WriteAllText((Join-Path $payloadRoot 'safe_read_runtime_attestation.v1.sha256'),$runtimePin+"`n",[Text.UTF8Encoding]::new($false))
    $targets += [ordered]@{revitYear=$year;framework=$expected.Framework;platform='x64';revitApi=$api;requiredPayload=$payload;proof=[ordered]@{path='proof/proof.receipt.json';sha256=$proofSha;sizeBytes=(Get-Item $proofPath).Length;artifactUnsignedSha256=('d'*64);managedCodeSha256=$managed};runtimeAttestation=[ordered]@{path='payload/safe_read_runtime_attestation.v1.json';sha256=$runtimePin;sizeBytes=(Get-Item $runtimePath).Length};manifest=[ordered]@{path='manifest/RevitOperator.SafeReadHost.addin.template';sha256=Get-SafeReadSha256 $template;sizeBytes=(Get-Item $template).Length}}
    $tuples += [ordered]@{revitYear=$year;runtimeAttestationSha256=$runtimePin}
  }
  $release=[ordered]@{schemaVersion='revit-operator.safe-read-package-release.v2';releaseId=$ReleaseId;allowedSignerThumbprints=@('TESTSIGNER');targets=$targets};$releasePath=Join-Path $Root 'release-manifest.json';Write-JsonFile $releasePath $release
  $pins=[ordered]@{schemaVersion='revit-operator.safe-read-package-pins.v2';releaseId=$ReleaseId;releaseManifestSha256=Get-SafeReadSha256 $releasePath;targets=$tuples};$pinsPath=Join-Path $Root 'package-pins.json';Write-JsonFile $pinsPath $pins
  [pscustomobject]@{Root=$Root;Pin=Get-SafeReadSha256 $pinsPath}
}
function Refresh-Attestation($Bundle){$pins=ConvertTo-SafeReadObject (Join-Path $Bundle.Root 'package-pins.json');$pins.releaseManifestSha256=Get-SafeReadSha256 (Join-Path $Bundle.Root 'release-manifest.json');Write-JsonFile (Join-Path $Bundle.Root 'package-pins.json') $pins;$Bundle.Pin=Get-SafeReadSha256 (Join-Path $Bundle.Root 'package-pins.json')}
function Refresh-RuntimeAttestation($Bundle,[string]$Year){$runtimePath=Join-Path $Bundle.Root "targets\$Year\payload\safe_read_runtime_attestation.v1.json";$runtimePin=Get-SafeReadSha256 $runtimePath;[IO.File]::WriteAllText((Join-Path $Bundle.Root "targets\$Year\payload\safe_read_runtime_attestation.v1.sha256"),$runtimePin+"`n",[Text.UTF8Encoding]::new($false));$release=ConvertTo-SafeReadObject (Join-Path $Bundle.Root 'release-manifest.json');$target=@($release.targets|Where-Object revitYear -eq $Year)[0];$target.runtimeAttestation.sha256=$runtimePin;$target.runtimeAttestation.sizeBytes=(Get-Item $runtimePath).Length;Write-JsonFile (Join-Path $Bundle.Root 'release-manifest.json') $release;$pins=ConvertTo-SafeReadObject (Join-Path $Bundle.Root 'package-pins.json');@($pins.targets|Where-Object revitYear -eq $Year)[0].runtimeAttestationSha256=$runtimePin;$pins.releaseManifestSha256=Get-SafeReadSha256 (Join-Path $Bundle.Root 'release-manifest.json');Write-JsonFile (Join-Path $Bundle.Root 'package-pins.json') $pins;$Bundle.Pin=Get-SafeReadSha256 (Join-Path $Bundle.Root 'package-pins.json')}

Describe 'SafeRead package v2 repair contract' {
  BeforeEach{$bundle=New-TestBundle (Join-Path $TestDrive ([guid]::NewGuid().ToString('N')))}
  It 'accepts only the exact host, certified executor, proof, and runtime attestation layout'{$withExecutor=New-TestBundle (Join-Path $TestDrive 'executor') 'safe-read-with-executor';&$verify -BundleRoot $withExecutor.Root -AttestationPinSha256 $withExecutor.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector;$template=Join-Path $withExecutor.Root 'targets\2023\manifest\RevitOperator.SafeReadHost.addin.template';[void](Assert-SafeReadManifestXml -Path $template -ExpectedAssembly '{{ASSEMBLY_PATH}}')}
  It 'binds backend host tuple fields to certified executor rather than transport host'{foreach($year in '2023','2024','2025'){$release=ConvertTo-SafeReadObject (Join-Path $bundle.Root 'release-manifest.json');$target=@($release.targets|Where-Object revitYear -eq $year)[0];$executor=@($target.requiredPayload|Where-Object role -eq 'certified_executor')[0];$hostPayloadItem=@($target.requiredPayload|Where-Object role -eq 'host')[0];$runtime=ConvertTo-SafeReadObject (Join-Path $bundle.Root "targets\$year\payload\safe_read_runtime_attestation.v1.json");if($runtime.runtime_tuple.host_content_sha256 -ne $executor.sha256 -or $runtime.runtime_tuple.host_mvid -ne $executor.assembly.mvid){throw 'Runtime tuple does not bind certified executor.'};if($runtime.runtime_tuple.host_content_sha256 -eq $hostPayloadItem.sha256){throw 'Runtime tuple accidentally binds transport host.'}}}
  It 'packages real three-year host build fixtures and derives their deterministic dependency closure'{
    $repositoryRoot=(Resolve-Path (Join-Path $deployRoot '..\..')).Path;$apis=@{};$hostOutputs=@{};foreach($year in '2023','2024','2025'){$tfm=if($year -eq '2025'){'net8.0-windows'}else{'net48'};$apis[$year]="C:\Program Files\Autodesk\Revit $year\RevitAPI.dll";$hostOutputs[$year]=Join-Path $repositoryRoot "apps\revit-safe-read-host\src\RevitOperator.SafeReadHost\bin\Revit$year\Release\$tfm";$project=Join-Path $repositoryRoot 'apps\revit-safe-read-host\src\RevitOperator.SafeReadHost\RevitOperator.SafeReadHost.csproj';$apiDirectory=Split-Path -Parent $apis[$year];& dotnet build $project -c Release -f $tfm -p:RevitYear=$year -p:Platform=x64 -p:RevitApiPath="$apiDirectory" --nologo;if($LASTEXITCODE -ne 0){throw "SafeRead host fixture build failed for $year."}}
    $proofBootstrap=Join-Path $TestDrive 'proof-bootstrap';& pwsh -NoProfile -File (Join-Path $repositoryRoot 'apps\revit-safe-read-proof\bootstrap.ps1') -Check -OutputRoot $proofBootstrap|Out-Null;if($LASTEXITCODE -ne 0){throw 'SafeRead proof-tool bootstrap failed.'};$proofTool=Join-Path $proofBootstrap 'tool\RevitSafeReadProof.dll'
    $proofRoot=Join-Path $TestDrive 'real-proof';New-Item -ItemType Directory -Path $proofRoot|Out-Null;$artifacts=[ordered]@{};foreach($year in '2023','2024','2025'){$source=Join-Path $hostOutputs[$year] 'RevitOperator.SafeReadCertifiedExecution.dll';$name="RevitOperator.SafeReadCertifiedExecution.Revit$year.dll";$path=Join-Path $proofRoot $name;Copy-Item -LiteralPath $source -Destination $path;$fingerprintRoot=Join-Path $TestDrive "unsigned-fingerprint-$year";& dotnet $proofTool fingerprint --artifact $path --output-dir $fingerprintRoot|Out-Null;if($LASTEXITCODE -ne 0){throw "Unsigned fingerprint failed for $year."};$fingerprint=ConvertTo-SafeReadObject (Join-Path $fingerprintRoot 'artifact.fingerprint.json');$facts=Get-SafeReadAssemblyFacts $path;$artifacts[$year]=[ordered]@{fileName=$name;sha256=(Get-SafeReadSha256 $path).Substring(7);length=(Get-Item $path).Length;managedCodeSha256=[string]$fingerprint.managedCodeSha256;assemblyIdentity=[string]$fingerprint.assemblyIdentity;targetFramework=$facts.TargetFramework;platform='x64'}}
    $receipt=[ordered]@{schemaVersion=1;proofKind='revit-safe-read-certified-kernel/v1';mode='check';status='verified';certified=$true;manifestSha256=('c'*64);trustBoundary='fixture-only';compilerOptions=@('fixture-only');issues=@();observation=[ordered]@{};artifacts=$artifacts};$receiptPath=Join-Path $proofRoot 'proof.receipt.json';Write-JsonFile $receiptPath $receipt
    $input=[ordered]@{schemaVersion='revit-operator.safe-read-package-build-input.v2';releaseId='real-fixture-package';allowedSignerThumbprints=@('TESTSIGNER');runtimeAttestation=[ordered]@{state='active';issued_at_utc='2030-01-01T00:00:00.000Z';expires_at_utc='2030-01-01T00:05:00.000Z';route_id='safe_read.sheet_count.v1';route_contract_sha256='sha256:cc80c231ba289396516164cb0fdbc3c71779ac018e717085f07a544530e68874';policy_sha256='sha256:23692b21a7e728e9c1ce5eec9580dcec4f3ac7f25d3d95059899c680a17aad67';executor_id='revit-operator.safe-read-host.v1'};targets=@()};foreach($year in '2023','2024','2025'){$expected=Get-SafeReadExpectedTarget $year;$input.targets += [ordered]@{revitYear=$year;framework=$expected.Framework;platform='x64';revitApiPath=$apis[$year];proofReceiptPath=$receiptPath;requiredPayload=@([ordered]@{fileName='RevitOperator.SafeReadHost.dll';role='host';revitApiBound=$true;sourceDll=(Join-Path $hostOutputs[$year] 'RevitOperator.SafeReadHost.dll')},[ordered]@{fileName='RevitOperator.SafeReadCertifiedExecution.dll';role='certified_executor';revitApiBound=$true})}}
    $inputPath=Join-Path $TestDrive 'real-build-input.json';Write-JsonFile $inputPath $input;$output=Join-Path $TestDrive 'real-output';New-Item -ItemType Directory -Path $output|Out-Null;&$builder -InputManifestPath $inputPath -OutputRoot $output -RepositoryRoot $repositoryRoot -SignFileAction {param($Path,$Year,$Item)if($Item.role -eq 'certified_executor'){Add-TestAuthenticodeCertificateTable $Path}} -SignatureVerifier $signatureVerifier -ProofToolPath $proofTool
    $built=Join-Path $output 'SafeReadPackage-real-fixture-package';$release=ConvertTo-SafeReadObject (Join-Path $built 'release-manifest.json');foreach($target in @($release.targets)){$executor=@($target.requiredPayload|Where-Object role -eq 'certified_executor')[0];if($executor.sha256 -ceq $executor.provenance.unsignedSha256){throw "Synthetic signing did not change the raw executor hash for $($target.revitYear)."};if($executor.provenance.managedCodeSha256 -cne [string]$artifacts[[string]$target.revitYear].managedCodeSha256){throw "Standalone post-sign fingerprint changed for $($target.revitYear)."}};$net48=@($release.targets|Where-Object revitYear -eq '2023')[0];if(-not(@($net48.requiredPayload|Where-Object role -eq 'runtime_dependency'|Where-Object{$_.assembly.name -eq 'System.Text.Json'}).Count)){throw 'net48 System.Text.Json dependency closure was not packaged.'};$net8=@($release.targets|Where-Object revitYear -eq '2025')[0];if(@($net8.requiredPayload|Where-Object role -eq 'runtime_dependency').Count){throw 'net8 package unexpectedly copied shared-framework dependencies.'}
  }
  It 'rejects malformed DTD XML and an extra AddIn'{
    $template=Join-Path $bundle.Root 'targets\2023\manifest\RevitOperator.SafeReadHost.addin.template';[IO.File]::WriteAllText($template,'<!DOCTYPE x [<!ENTITY y "z">]><RevitAddIns/>');Assert-ThrowsLike {[void](Assert-SafeReadManifestXml -Path $template -ExpectedAssembly '{{ASSEMBLY_PATH}}')} '*DTD*'
    $valid=Get-Content -LiteralPath (Resolve-Path (Join-Path $deployRoot '..\..\apps\revit-safe-read-host\addin\RevitOperator.SafeReadHost.addin.template')) -Raw;$extra=$valid.Replace('</RevitAddIns>',$valid.Substring($valid.IndexOf('<AddIn'),$valid.IndexOf('</AddIn>')+8-$valid.IndexOf('<AddIn'))+'</RevitAddIns>');[IO.File]::WriteAllText($template,$extra);Assert-ThrowsLike {[void](Assert-SafeReadManifestXml -Path $template -ExpectedAssembly '{{ASSEMBLY_PATH}}')} '*exactly one AddIn*'
  }
  It 'rejects a cross-year assembly even when hashes and attestation are internally consistent'{$cross={param($Path,$Year,$Item)$facts=Get-TestFacts $Year ([IO.Path]::GetFileNameWithoutExtension($Path));if($Year -eq '2023'){$facts.RevitApiReferenceVersion='24.0.0.0'};$facts};Assert-ThrowsLike {&$verify -BundleRoot $bundle.Root -AttestationPinSha256 $bundle.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $cross} '*cross-year*'}
  It 'rejects dynamic host or document fields in the static package attestation'{$path=Join-Path $bundle.Root 'targets\2024\payload\safe_read_runtime_attestation.v1.json';$attestation=ConvertTo-SafeReadObject $path;$attestation|Add-Member -NotePropertyName host_instance_id -NotePropertyValue 'must-not-be-packaged';Write-JsonFile $path $attestation;Refresh-RuntimeAttestation $bundle '2024';Assert-ThrowsLike {&$verify -BundleRoot $bundle.Root -AttestationPinSha256 $bundle.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*extra properties*'}
  It 'rejects missing or renamed certified executor and an incomplete dependency closure'{
    $missing=New-TestBundle (Join-Path $TestDrive 'missing-executor') 'missing-executor';Remove-Item -LiteralPath (Join-Path $missing.Root 'targets\2023\payload\RevitOperator.SafeReadCertifiedExecution.dll');Assert-ThrowsLike {&$verify -BundleRoot $missing.Root -AttestationPinSha256 $missing.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*missing or extra*'
    $wrong=New-TestBundle (Join-Path $TestDrive 'wrong-executor') 'wrong-executor';$release=ConvertTo-SafeReadObject (Join-Path $wrong.Root 'release-manifest.json');@($release.targets[0].requiredPayload|Where-Object role -eq 'certified_executor')[0].path='payload/Wrong.dll';Write-JsonFile (Join-Path $wrong.Root 'release-manifest.json') $release;Refresh-Attestation $wrong;Assert-ThrowsLike {&$verify -BundleRoot $wrong.Root -AttestationPinSha256 $wrong.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*exactly one certified executor*'
    $dependency=New-TestBundle (Join-Path $TestDrive 'dependency') 'dependency';$release=ConvertTo-SafeReadObject (Join-Path $dependency.Root 'release-manifest.json');@($release.targets[0].requiredPayload|Where-Object role -eq 'host')[0].assembly.references=@('Missing.Runtime.Dependency');Write-JsonFile (Join-Path $dependency.Root 'release-manifest.json') $release;Refresh-Attestation $dependency;Assert-ThrowsLike {&$verify -BundleRoot $dependency.Root -AttestationPinSha256 $dependency.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*missing runtime dependency*'
  }
  It 'rejects missing or tampered proof evidence and a tuple that does not bind the executor'{
    $missingProof=New-TestBundle (Join-Path $TestDrive 'missing-proof') 'missing-proof';Remove-Item -LiteralPath (Join-Path $missingProof.Root 'targets\2023\proof\proof.receipt.json');Assert-ThrowsLike {&$verify -BundleRoot $missingProof.Root -AttestationPinSha256 $missingProof.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*missing or extra*'
    $tamperedProof=New-TestBundle (Join-Path $TestDrive 'tampered-proof') 'tampered-proof';$tamperedProofPath=Join-Path $tamperedProof.Root 'targets\2024\proof\proof.receipt.json';$tamperedReceipt=ConvertTo-SafeReadObject $tamperedProofPath;$tamperedReceipt.artifacts.'2024'.managedCodeSha256=('0'*64);Write-JsonFile $tamperedProofPath $tamperedReceipt;Assert-ThrowsLike {&$verify -BundleRoot $tamperedProof.Root -AttestationPinSha256 $tamperedProof.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*proof evidence does not bind*'
    $wrongTuple=New-TestBundle (Join-Path $TestDrive 'wrong-tuple') 'wrong-tuple';$runtimePath=Join-Path $wrongTuple.Root 'targets\2025\payload\safe_read_runtime_attestation.v1.json';$runtime=ConvertTo-SafeReadObject $runtimePath;$runtime.runtime_tuple.host_content_sha256='sha256:'+('0'*64);Write-JsonFile $runtimePath $runtime;Refresh-RuntimeAttestation $wrongTuple '2025';Assert-ThrowsLike {&$verify -BundleRoot $wrongTuple.Root -AttestationPinSha256 $wrongTuple.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*does not match certified executor*'
  }
  It 'rejects missing, extra, tampered, and stale-pinned package trees'{
    $missing=New-TestBundle (Join-Path $TestDrive 'missing') 'missing-test';Remove-Item -LiteralPath (Join-Path $missing.Root 'targets\2023\payload\RevitOperator.SafeReadHost.dll');Assert-ThrowsLike {&$verify -BundleRoot $missing.Root -AttestationPinSha256 $missing.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*missing or extra*'
    $extra=New-TestBundle (Join-Path $TestDrive 'extra') 'extra-test';[IO.File]::WriteAllText((Join-Path $extra.Root 'targets\2024\payload\unexpected.dll'),'x');Assert-ThrowsLike {&$verify -BundleRoot $extra.Root -AttestationPinSha256 $extra.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*missing or extra*'
    $tampered=New-TestBundle (Join-Path $TestDrive 'tampered') 'tampered-test';[IO.File]::AppendAllText((Join-Path $tampered.Root 'targets\2025\payload\RevitOperator.SafeReadHost.dll'),'tamper');Assert-ThrowsLike {&$verify -BundleRoot $tampered.Root -AttestationPinSha256 $tampered.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*hash/size mismatch*'
    Assert-ThrowsLike {&$verify -BundleRoot $bundle.Root -AttestationPinSha256 ('sha256:'+('0'*64)) -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*pin does not match*'
  }
  It 'rejects payload and rollback release path traversal'{$release=ConvertTo-SafeReadObject (Join-Path $bundle.Root 'release-manifest.json');$release.targets[0].requiredPayload[0].path='payload/../evil.dll';Write-JsonFile (Join-Path $bundle.Root 'release-manifest.json') $release;Refresh-Attestation $bundle;Assert-ThrowsLike {&$verify -BundleRoot $bundle.Root -AttestationPinSha256 $bundle.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*Unsafe*';Assert-ThrowsLike {&$install -RollbackReleaseId '..\evil' -DestinationRoot (Join-Path $TestDrive 'install') -RevitAddinsRoot (Join-Path $TestDrive 'addins') -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*releaseId is invalid*'}
  It 'pre-stages all manifests and restores a coherent prior activation after a partial write failure'{
    $destination=Join-Path $TestDrive 'Install&Root';$addins=Join-Path $TestDrive 'Addins';New-Item -ItemType Directory -Force -Path (Join-Path $addins '2023')|Out-Null;$main=Join-Path $addins '2023\RevitBridge.addin';[IO.File]::WriteAllText($main,'<main/>')
    &$install -BundleRoot $bundle.Root -AttestationPinSha256 $bundle.Pin -DestinationRoot $destination -RevitAddinsRoot $addins -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector
    $second=New-TestBundle (Join-Path $TestDrive 'second') 'safe-read-v2-b';$writer={param($Path,$Content,$Index,$Phase)if($Index -eq 1){throw 'injected partial write'};Write-SafeReadAtomicFile -Path $Path -Content $Content}
    Assert-ThrowsLike {&$install -BundleRoot $second.Root -AttestationPinSha256 $second.Pin -DestinationRoot $destination -RevitAddinsRoot $addins -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector -ManifestWriter $writer} '*injected partial write*'
    $active=ConvertTo-SafeReadObject (Join-Path $destination 'active-release.json');if($active.releaseId -ne 'safe-read-v2-a'){throw 'Activation pointer changed after partial failure.'};foreach($year in '2023','2024','2025'){$manifest=Get-Content -LiteralPath (Join-Path $addins "$year\RevitOperator.SafeReadHost.addin") -Raw;if($manifest -notlike '*safe-read-v2-a*' -or $manifest -like '*safe-read-v2-b*'){throw "Manifest $year is incoherent after partial failure."};if($manifest -notlike '*Install&amp;Root*'){throw 'Installed assembly path was not XML-escaped.'}};if((Get-Content $main -Raw)-ne'<main/>'){throw 'Main manifest changed.'}
    &$install -RollbackReleaseId 'safe-read-v2-b' -DestinationRoot $destination -RevitAddinsRoot $addins -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector;&$install -RollbackReleaseId 'safe-read-v2-a' -DestinationRoot $destination -RevitAddinsRoot $addins -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector;$active=ConvertTo-SafeReadObject (Join-Path $destination 'active-release.json');if($active.releaseId -ne 'safe-read-v2-a'){throw 'Verified rollback did not reactivate the original release.'}
  }
  It 'refuses rollback when an installed certified executor was tampered'{
    $destination=Join-Path $TestDrive 'rollback-install';$addins=Join-Path $TestDrive 'rollback-addins';&$install -BundleRoot $bundle.Root -AttestationPinSha256 $bundle.Pin -DestinationRoot $destination -RevitAddinsRoot $addins -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector
    [IO.File]::AppendAllText((Join-Path $destination 'releases\safe-read-v2-a\targets\2024\payload\RevitOperator.SafeReadCertifiedExecution.dll'),'tamper')
    Assert-ThrowsLike {&$install -RollbackReleaseId 'safe-read-v2-a' -DestinationRoot $destination -RevitAddinsRoot $addins -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*hash/size mismatch*'
  }
}
