$ErrorActionPreference='Stop'
$deployRoot=Split-Path -Parent $PSScriptRoot
$module=Join-Path $deployRoot 'SafeReadPackageV2.psm1';$verify=Join-Path $deployRoot 'verify_saferead_microhost_bundle.ps1';$install=Join-Path $deployRoot 'install_saferead_microhost_bundle.ps1';$builder=Join-Path $deployRoot 'build_saferead_package_v2.ps1'
Import-Module $module -Force

function Write-JsonFile([string]$Path,$Value){[IO.File]::WriteAllText($Path,(ConvertTo-SafeReadCanonicalJson $Value),[Text.UTF8Encoding]::new($false))}
function Assert-ThrowsLike([scriptblock]$Action,[string]$Pattern){try{&$Action}catch{if($_.Exception.Message -like $Pattern){return};throw "Expected '$Pattern', got '$($_.Exception.Message)'."};throw "Expected '$Pattern', but action succeeded."}
function Get-TestFacts([string]$Year,[string]$Name='RevitOperator.SafeReadHost'){$expected=Get-SafeReadExpectedTarget $Year;[pscustomobject]@{Name=$Name;TargetFramework=$expected.TargetFrameworkAttribute;Platform='Amd64';Mvid=('00000000-0000-0000-0000-{0}' -f $Year.PadLeft(12,'0'));RevitApiReferenceVersion=('{0}.0.0.0' -f $expected.RevitApiMajor)}}
$signatureVerifier={param($Path)[pscustomobject]@{Status='Valid';Thumbprint='TESTSIGNER'}}
$assemblyInspector={param($Path,$Year,$Item)Get-TestFacts $Year ([IO.Path]::GetFileNameWithoutExtension($Path))}

function New-TestBundle([string]$Root,[string]$ReleaseId='safe-read-v2-a',[switch]$IncludeExecutor){
  $templateSource=Resolve-Path (Join-Path $deployRoot '..\..\apps\revit-safe-read-host\addin\RevitOperator.SafeReadHost.addin.template')
  New-Item -ItemType Directory -Force -Path $Root|Out-Null;$targets=@();$tuples=@()
  foreach($year in '2023','2024','2025'){
    $expected=Get-SafeReadExpectedTarget $year;$targetRoot=Join-Path $Root "targets\$year";$payloadRoot=Join-Path $targetRoot 'payload';$manifestRoot=Join-Path $targetRoot 'manifest';New-Item -ItemType Directory -Force -Path $payloadRoot,$manifestRoot|Out-Null
    $items=@([ordered]@{fileName='RevitOperator.SafeReadHost.dll';role='host';revitApiBound=$true})
    if($IncludeExecutor){$items+= [ordered]@{fileName='RevitOperator.SafeReadCertifiedExecution.dll';role='certified_executor';revitApiBound=$true}}
    $payload=@()
    foreach($item in $items){$path=Join-Path $payloadRoot $item.fileName;[IO.File]::WriteAllText($path,"$year-$($item.role)",[Text.UTF8Encoding]::new($false));$facts=Get-TestFacts $year ([IO.Path]::GetFileNameWithoutExtension($item.fileName));$payload += [ordered]@{path="payload/$($item.fileName)";role=$item.role;revitApiBound=$item.revitApiBound;sha256=Get-SafeReadSha256 $path;sizeBytes=(Get-Item $path).Length;assembly=[ordered]@{name=$facts.Name;targetFramework=$facts.TargetFramework;platform=$facts.Platform;mvid=$facts.Mvid;revitApiReferenceVersion=$facts.RevitApiReferenceVersion}}}
    $template=Join-Path $manifestRoot 'RevitOperator.SafeReadHost.addin.template';Copy-Item -LiteralPath $templateSource -Destination $template
    $api=[ordered]@{contentSha256=('sha256:'+($year[0].ToString()*64));mvid=('10000000-0000-0000-0000-{0}' -f $year.PadLeft(12,'0'));assemblyVersion=('{0}.0.0.0' -f $expected.RevitApiMajor)}
    $targets += [ordered]@{revitYear=$year;framework=$expected.Framework;platform='x64';revitApi=$api;requiredPayload=$payload;manifest=[ordered]@{path='manifest/RevitOperator.SafeReadHost.addin.template';sha256=Get-SafeReadSha256 $template;sizeBytes=(Get-Item $template).Length}}
    $hostPayload=@($payload|Where-Object role -eq 'host')[0];$tuples += [ordered]@{revit_version=$year;runtime_tuple=[ordered]@{host_content_sha256=$hostPayload.sha256;host_mvid=$hostPayload.assembly.mvid;revit_api_content_sha256=$api.contentSha256;revit_api_mvid=$api.mvid;revit_version=$year}}
  }
  $release=[ordered]@{schemaVersion='revit-operator.safe-read-package-release.v2';releaseId=$ReleaseId;allowedSignerThumbprints=@('TESTSIGNER');targets=$targets};$releasePath=Join-Path $Root 'release-manifest.json';Write-JsonFile $releasePath $release
  $attestation=[ordered]@{schemaVersion='revit-operator.safe-read-package-attestation.v2';releaseId=$ReleaseId;releaseManifestSha256=Get-SafeReadSha256 $releasePath;staticRuntimeTuples=$tuples};$attestationPath=Join-Path $Root 'deployment-attestation.json';Write-JsonFile $attestationPath $attestation
  [pscustomobject]@{Root=$Root;Pin=Get-SafeReadSha256 $attestationPath}
}
function Refresh-Attestation($Bundle){$release=ConvertTo-SafeReadObject (Join-Path $Bundle.Root 'release-manifest.json');$attestation=ConvertTo-SafeReadObject (Join-Path $Bundle.Root 'deployment-attestation.json');$attestation.releaseManifestSha256=Get-SafeReadSha256 (Join-Path $Bundle.Root 'release-manifest.json');Write-JsonFile (Join-Path $Bundle.Root 'deployment-attestation.json') $attestation;$Bundle.Pin=Get-SafeReadSha256 (Join-Path $Bundle.Root 'deployment-attestation.json')}

Describe 'SafeRead package v2 repair contract' {
  BeforeEach{$bundle=New-TestBundle (Join-Path $TestDrive ([guid]::NewGuid().ToString('N')))}
  It 'accepts the real layout, permanent identity, same AddInId, and parameterized exact executor payload'{$withExecutor=New-TestBundle (Join-Path $TestDrive 'executor') 'safe-read-with-executor' -IncludeExecutor;&$verify -BundleRoot $withExecutor.Root -AttestationPinSha256 $withExecutor.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector;$template=Join-Path $withExecutor.Root 'targets\2023\manifest\RevitOperator.SafeReadHost.addin.template';[void](Assert-SafeReadManifestXml -Path $template -ExpectedAssembly '{{ASSEMBLY_PATH}}')}
  It 'builds the actual core project for all years and emits backend-shaped static tuples only'{
    $apis=@('2023','2024','2025'|ForEach-Object{"C:\Program Files\Autodesk\Revit $_\RevitAPI.dll"});if(@($apis|Where-Object{-not(Test-Path $_)}).Count){return}
    $input=[ordered]@{schemaVersion='revit-operator.safe-read-package-build-input.v2';releaseId='real-layout-test';allowedSignerThumbprints=@('TESTSIGNER');targets=@()}
    foreach($year in '2023','2024','2025'){$expected=Get-SafeReadExpectedTarget $year;$input.targets += [ordered]@{revitYear=$year;framework=$expected.Framework;platform='x64';revitApiPath="C:\Program Files\Autodesk\Revit $year\RevitAPI.dll";requiredPayload=@([ordered]@{fileName='RevitOperator.SafeReadHost.dll';role='host';revitApiBound=$true})}}
    $inputPath=Join-Path $TestDrive 'build-input.json';Write-JsonFile $inputPath $input;$output=Join-Path $TestDrive 'output';New-Item -ItemType Directory -Path $output|Out-Null
    &$builder -InputManifestPath $inputPath -OutputRoot $output -RepositoryRoot (Resolve-Path (Join-Path $deployRoot '..\..')).Path -SignFileAction {param($Path,$Year,$Item)} -SignatureVerifier $signatureVerifier
    $built=Join-Path $output 'SafeReadPackage-real-layout-test';$attestation=ConvertTo-SafeReadObject (Join-Path $built 'deployment-attestation.json');if($attestation.PSObject.Properties.Name -contains 'host_instance_id' -or $attestation.PSObject.Properties.Name -contains 'document'){throw 'Package attestation contains dynamic host/document binding.'};foreach($tuple in $attestation.staticRuntimeTuples){if($tuple.runtime_tuple.host_content_sha256 -cnotmatch '^sha256:[0-9a-f]{64}$'){throw 'Tuple hash format is not backend-compatible.'}}
  }
  It 'rejects malformed DTD XML and an extra AddIn'{
    $template=Join-Path $bundle.Root 'targets\2023\manifest\RevitOperator.SafeReadHost.addin.template';[IO.File]::WriteAllText($template,'<!DOCTYPE x [<!ENTITY y "z">]><RevitAddIns/>');Assert-ThrowsLike {[void](Assert-SafeReadManifestXml -Path $template -ExpectedAssembly '{{ASSEMBLY_PATH}}')} '*DTD*'
    $valid=Get-Content -LiteralPath (Resolve-Path (Join-Path $deployRoot '..\..\apps\revit-safe-read-host\addin\RevitOperator.SafeReadHost.addin.template')) -Raw;$extra=$valid.Replace('</RevitAddIns>',$valid.Substring($valid.IndexOf('<AddIn'),$valid.IndexOf('</AddIn>')+8-$valid.IndexOf('<AddIn'))+'</RevitAddIns>');[IO.File]::WriteAllText($template,$extra);Assert-ThrowsLike {[void](Assert-SafeReadManifestXml -Path $template -ExpectedAssembly '{{ASSEMBLY_PATH}}')} '*exactly one AddIn*'
  }
  It 'rejects a cross-year assembly even when hashes and attestation are internally consistent'{$cross={param($Path,$Year,$Item)$facts=Get-TestFacts $Year ([IO.Path]::GetFileNameWithoutExtension($Path));if($Year -eq '2023'){$facts.RevitApiReferenceVersion='24.0.0.0'};$facts};Assert-ThrowsLike {&$verify -BundleRoot $bundle.Root -AttestationPinSha256 $bundle.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $cross} '*cross-year*'}
  It 'rejects dynamic host or document fields in the static package attestation'{$attestation=ConvertTo-SafeReadObject (Join-Path $bundle.Root 'deployment-attestation.json');$attestation|Add-Member -NotePropertyName host_instance_id -NotePropertyValue 'must-not-be-packaged';Write-JsonFile (Join-Path $bundle.Root 'deployment-attestation.json') $attestation;$bundle.Pin=Get-SafeReadSha256 (Join-Path $bundle.Root 'deployment-attestation.json');Assert-ThrowsLike {&$verify -BundleRoot $bundle.Root -AttestationPinSha256 $bundle.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*extra properties*'}
  It 'rejects missing, extra, tampered, and stale-pinned package trees'{
    $missing=New-TestBundle (Join-Path $TestDrive 'missing') 'missing-test';Remove-Item -LiteralPath (Join-Path $missing.Root 'targets\2023\payload\RevitOperator.SafeReadHost.dll');Assert-ThrowsLike {&$verify -BundleRoot $missing.Root -AttestationPinSha256 $missing.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*missing or extra*'
    $extra=New-TestBundle (Join-Path $TestDrive 'extra') 'extra-test';[IO.File]::WriteAllText((Join-Path $extra.Root 'targets\2024\payload\unexpected.dll'),'x');Assert-ThrowsLike {&$verify -BundleRoot $extra.Root -AttestationPinSha256 $extra.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*missing or extra*'
    $tampered=New-TestBundle (Join-Path $TestDrive 'tampered') 'tampered-test';[IO.File]::AppendAllText((Join-Path $tampered.Root 'targets\2025\payload\RevitOperator.SafeReadHost.dll'),'tamper');Assert-ThrowsLike {&$verify -BundleRoot $tampered.Root -AttestationPinSha256 $tampered.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*hash/size mismatch*'
    Assert-ThrowsLike {&$verify -BundleRoot $bundle.Root -AttestationPinSha256 ('sha256:'+('0'*64)) -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*pin does not match*'
  }
  It 'rejects payload and rollback release path traversal'{$release=ConvertTo-SafeReadObject (Join-Path $bundle.Root 'release-manifest.json');$release.targets[0].requiredPayload[0].path='payload/../evil.dll';Write-JsonFile (Join-Path $bundle.Root 'release-manifest.json') $release;Refresh-Attestation $bundle;Assert-ThrowsLike {&$verify -BundleRoot $bundle.Root -AttestationPinSha256 $bundle.Pin -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*Unsafe*';Assert-ThrowsLike {&$install -RollbackReleaseId '..\evil' -DestinationRoot (Join-Path $TestDrive 'install') -RevitAddinsRoot (Join-Path $TestDrive 'addins') -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector} '*releaseId is invalid*'}
  It 'pre-stages all manifests and restores a coherent prior activation after a partial write failure'{
    $destination=Join-Path $TestDrive 'Install&Root';$addins=Join-Path $TestDrive 'Addins';New-Item -ItemType Directory -Force -Path (Join-Path $addins '2023')|Out-Null;$main=Join-Path $addins '2023\RevitBridge.addin';[IO.File]::WriteAllText($main,'<main/>')
    &$install -BundleRoot $bundle.Root -AttestationPinSha256 $bundle.Pin -DestinationRoot $destination -RevitAddinsRoot $addins -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector
    $second=New-TestBundle (Join-Path $TestDrive 'second') 'safe-read-v2-b';$writer={param($Path,$Content,$Index,$Phase)if($Index -eq 1){throw 'injected partial write'};Write-SafeReadAtomicFile -Path $Path -Content $Content}
    Assert-ThrowsLike {&$install -BundleRoot $second.Root -AttestationPinSha256 $second.Pin -DestinationRoot $destination -RevitAddinsRoot $addins -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector -ManifestWriter $writer} '*injected partial write*'
    $active=ConvertTo-SafeReadObject (Join-Path $destination 'active-release.json');if($active.releaseId -ne 'safe-read-v2-a'){throw 'Activation pointer changed after partial failure.'};foreach($year in '2023','2024','2025'){$manifest=Get-Content -LiteralPath (Join-Path $addins "$year\RevitOperator.SafeReadHost.addin") -Raw;if($manifest -notlike '*safe-read-v2-a*' -or $manifest -like '*safe-read-v2-b*'){throw "Manifest $year is incoherent after partial failure."};if($manifest -notlike '*Install&amp;Root*'){throw 'Installed assembly path was not XML-escaped.'}};if((Get-Content $main -Raw)-ne'<main/>'){throw 'Main manifest changed.'}
    &$install -RollbackReleaseId 'safe-read-v2-b' -DestinationRoot $destination -RevitAddinsRoot $addins -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector;&$install -RollbackReleaseId 'safe-read-v2-a' -DestinationRoot $destination -RevitAddinsRoot $addins -SignatureVerifier $signatureVerifier -AssemblyInspector $assemblyInspector;$active=ConvertTo-SafeReadObject (Join-Path $destination 'active-release.json');if($active.releaseId -ne 'safe-read-v2-a'){throw 'Verified rollback did not reactivate the original release.'}
  }
}
