import { randomUUID } from "node:crypto";
import { types } from "node:util";
import { groundRedlineEvidenceTarget } from "../redline/redline_target_grounding.js";
import { AEC_INTENT_EVIDENCE_MAX_ARRAY_ITEMS, AEC_INTENT_EVIDENCE_MAX_STRING_CHARS, normalizeAecIntentEvidenceV1 } from "../aec_intent_evidence.js";
import type { WorkbenchActionResult } from "../workbench/workbench_runner.js";
import { callBridgeActionDirect } from "./direct_revit_bridge.js";

type GroundingPath = "/revit/sheets" | "/revit/get-titleblock-info";
type JsonRecord = Record<string, unknown>;
export type GroundingBridgeCall = (sessionId: string, method: "POST", path: GroundingPath, body: Record<string, unknown>) => Promise<{ ok: boolean; method: "GET" | "POST"; path: string; result_json?: unknown }>;
export type RedlineGroundingRuntimeDeps = { callBridge?: GroundingBridgeCall; createActionId?: () => string; };

function original(results: readonly WorkbenchActionResult[]): WorkbenchActionResult[] { return results.map((item) => ({ ...item, ...(item.details ? { details: { ...item.details } } : {}) })); }
function record(value: unknown): JsonRecord | null { return !!value && typeof value === "object" && !Array.isArray(value) && Object.getPrototypeOf(value) === Object.prototype ? value as JsonRecord : null; }
function exact(value: unknown, expected: JsonRecord): boolean { const item = record(value); return !!item && Object.keys(item).length === Object.keys(expected).length && Object.entries(expected).every(([key, entry]) => item[key] === entry); }
function actionId(value: unknown): value is string { return typeof value === "string" && !!value.trim() && value.length <= 512; }
function fingerprinted(evidence: ReturnType<typeof normalizeAecIntentEvidenceV1>): boolean { const fingerprint = evidence.target.document?.fingerprint, sources = new Set(evidence.evidence.filter((item) => (item.kind === "pdf_page" || item.kind === "pdf_annotation" || item.kind === "sheet_region") && item.source.kind === "adapter" && /^artifact:\/\//.test(item.uri ?? "") && typeof item.sha256 === "string" && /^[a-f0-9]{64}$/i.test(item.sha256)).map((item) => item.sha256!.toLowerCase())); return typeof fingerprint === "string" && /^[a-f0-9]{64}$/i.test(fingerprint) && sources.size === 1 && sources.has(fingerprint.toLowerCase()); }
function safeJsonSnapshot(value: unknown): { value: unknown } | null { const bad = Symbol("bad"), seen = new WeakSet<object>(); let nodes = 0; const copy = (source: unknown, depth: number): unknown | typeof bad => { if (++nodes > 10_000 || depth > 32 || source === undefined || typeof source === "function" || typeof source === "symbol" || typeof source === "bigint") return bad; if (source === null || typeof source === "boolean") return source; if (typeof source === "string") return source.length <= AEC_INTENT_EVIDENCE_MAX_STRING_CHARS ? source : bad; if (typeof source === "number") return Number.isFinite(source) ? source : bad; if (!source || typeof source !== "object" || seen.has(source)) return bad; try { if (typeof types.isProxy === "function" && types.isProxy(source)) return bad; seen.add(source); if (Array.isArray(source)) { const keys = Reflect.ownKeys(source), length = Object.getOwnPropertyDescriptor(source, "length"); if (Object.getPrototypeOf(source) !== Array.prototype || !length || !("value" in length) || typeof length.value !== "number" || !Number.isSafeInteger(length.value) || length.value < 0 || length.value > AEC_INTENT_EVIDENCE_MAX_ARRAY_ITEMS || keys.length !== length.value + 1 || keys.some((key) => key !== "length" && (typeof key !== "string" || !/^(0|[1-9]\d*)$/.test(key) || Number(key) >= length.value))) return bad; const out: unknown[] = []; for (let index = 0; index < length.value; index++) { const descriptor = Object.getOwnPropertyDescriptor(source, String(index)); if (!descriptor || !descriptor.enumerable || !("value" in descriptor)) return bad; const item = copy(descriptor.value, depth + 1); if (item === bad) return bad; out.push(item); } return out; } if (Object.getPrototypeOf(source) !== Object.prototype) return bad; const keys = Reflect.ownKeys(source); if (keys.length > AEC_INTENT_EVIDENCE_MAX_ARRAY_ITEMS || keys.some((key) => typeof key !== "string" || key.length > AEC_INTENT_EVIDENCE_MAX_STRING_CHARS)) return bad; const entries: Array<[string, unknown]> = []; for (const key of keys) { const descriptor = Object.getOwnPropertyDescriptor(source, key); if (typeof key !== "string" || !descriptor || !descriptor.enumerable || !("value" in descriptor)) return bad; entries.push([key, descriptor.value]); } const out: JsonRecord = {}; for (const [key, entry] of entries) { const item = copy(entry, depth + 1); if (item === bad) return bad; Object.defineProperty(out, key, { value: item, enumerable: true, configurable: true, writable: true }); } return out; } catch { return bad; } finally { seen.delete(source); } }; const copied = copy(value, 0); return copied === bad ? null : { value: copied }; }
function snapshotBridgeResult(raw: unknown, action: { method: "POST"; path: GroundingPath }): JsonRecord | null { const response = safeJsonSnapshot(raw), item = record(response?.value); return item?.ok === true && item.method === action.method && item.path === action.path ? record(item.result_json) : null; }
function probeTitleblock(sheet: JsonRecord): JsonRecord { const titleblock = Array.isArray(sheet.titleBlocks) ? record(sheet.titleBlocks[0]) : null; return { ok: true, sheetId: sheet.sheetId, sheetViewId: sheet.viewId, sheetNumber: sheet.sheetNumber, titleblockInstanceId: titleblock?.elementId, titleblockTypeId: titleblock?.typeId, titleblockCount: sheet.titleBlockCount }; }
function eligibleProbe(evidence: ReturnType<typeof normalizeAecIntentEvidenceV1>, actions: JsonRecord[], sheet: JsonRecord): boolean { let probe; try { probe = groundRedlineEvidenceTarget(evidence, { actions, results: [{ action_id: actions[0]!.action_id, method: "POST", path: "/revit/sheets", status: "done", result_json: sheet }, { action_id: actions[1]!.action_id, method: "POST", path: "/revit/get-titleblock-info", status: "done", result_json: probeTitleblock(sheet) }] }); } catch { return false; } return !!probe && probe.target.status === "ambiguous" && JSON.stringify(probe.target.document ?? null) === JSON.stringify(evidence.target.document ?? null) && typeof probe.target.sheet?.id === "number" && Number.isSafeInteger(probe.target.sheet.id) && probe.target.sheet.id > 0 && probe.target.sheet.number === evidence.target.sheet?.number && typeof probe.target.view?.id === "number" && Number.isSafeInteger(probe.target.view.id) && probe.target.view.id > 0 && typeof probe.target.view.name === "string" && !!probe.target.view.name; }

/** Executes the two accepted no-write discovery reads once and exposes only grounded evidence. */
export async function groundInitialRedlineWorkbenchResults(sessionId: string, results: readonly WorkbenchActionResult[], deps: RedlineGroundingRuntimeDeps = {}): Promise<WorkbenchActionResult[]> {
  const unchanged = original(results), candidates = unchanged.filter((item) => item.ok && item.type === "analyze_redline" && record(item.details)?.aec_intent_evidence);
  if (candidates.length !== 1) return unchanged;
  const candidate = candidates[0]!, details = record(candidate.details), evidence = details?.aec_intent_evidence;
  let normalized; try { normalized = normalizeAecIntentEvidenceV1(evidence); } catch { return unchanged; }
  const sheetNumber = normalized.target.status === "ambiguous" && typeof normalized.target.sheet?.number === "string" ? normalized.target.sheet.number : "", proposals = normalized.intent.proposed_actions;
  if (!fingerprinted(normalized) || normalized.intent.domain !== "redline" || normalized.intent.action !== "interpret_redline" || !sheetNumber || proposals.length !== 2 || proposals[0]?.tool !== "/revit/sheets" || proposals[1]?.tool !== "/revit/get-titleblock-info" || proposals.some((proposal) => proposal.requires_apply) || !exact(proposals[0]?.body, { action: "detail", sheetNumber, includePlacedViews: true, includeViewports: true, includeViewportGeometry: true, includeTitleBlocks: true, includeSheetOutline: true }) || !exact(proposals[1]?.body, { sheetNumber })) return unchanged;
  const create = deps.createActionId ?? randomUUID, firstId = create(), secondId = create();
  if (!actionId(firstId) || !actionId(secondId) || firstId === secondId) return unchanged;
  const actions = [{ action_id: firstId, method: "POST" as const, path: "/revit/sheets" as const, body: { action: "detail", sheetNumber, includePlacedViews: true, includeViewports: true, includeViewportGeometry: true, includeTitleBlocks: true, includeSheetOutline: true } }, { action_id: secondId, method: "POST" as const, path: "/revit/get-titleblock-info" as const, body: { sheetNumber } }];
  const call = deps.callBridge ?? callBridgeActionDirect as GroundingBridgeCall, firstAction = actions[0]!, secondAction = actions[1]!;
  let first: JsonRecord; try { first = snapshotBridgeResult(await call(sessionId, firstAction.method, firstAction.path, firstAction.body), firstAction) ?? null!; } catch { return unchanged; } if (!first || !eligibleProbe(normalized, actions as JsonRecord[], first)) return unchanged;
  let second: JsonRecord; try { second = snapshotBridgeResult(await call(sessionId, secondAction.method, secondAction.path, secondAction.body), secondAction) ?? null!; } catch { return unchanged; } if (!second) return unchanged;
  const received: JsonRecord[] = [{ action_id: firstAction.action_id, method: firstAction.method, path: firstAction.path, status: "done", result_json: first }, { action_id: secondAction.action_id, method: secondAction.method, path: secondAction.path, status: "done", result_json: second }];
  const grounded = groundRedlineEvidenceTarget(evidence, { actions, results: received });
  if (!grounded || grounded.target.status !== "ambiguous" || grounded.target.sheet?.id === undefined || grounded.target.view?.id === undefined) return unchanged;
  return unchanged.map((item) => item === candidate ? { ...item, details: { ...details, aec_intent_evidence: grounded } } : item);
}
