import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { __testOnlyBuildInitialRedlinePreflightAction, __testOnlyIsFastElectricalPlacementRedline, __testOnlyRunInitialRedlineDecisionLane, __testOnlyShouldPrioritizeInitialRedlinePreflight } from "../src/brains/openai_brain.js";
import { __testOnlyMaybeRunTopLevelMepRouteRedline } from "../src/brain.js";
import { adaptRedlineAnalyzeToAecIntentEvidence } from "../src/redline/redline_analyze_evidence.js";
import { AEC_INTENT_EVIDENCE_MAX_STRING_CHARS } from "../src/aec_intent_evidence.js";
import { executeWorkbenchActions } from "../src/workbench/workbench_runner.js";
import { groundInitialRedlineWorkbenchResults } from "../src/brains/redline_target_grounding_runtime.js";
import { buildCommentedPdf } from "./fixtures/commented_pdf.js";

const attachment = [{ id: "duct-redline", filename: "duct.pdf", relative_path: "artifacts/uploads/duct.pdf", mime: "application/pdf" }] as any;
const readOnlyPrompt = "Analyze the attached duct redline for deterministic intent evidence only; do not create/edit/delete/write.";
const failedLivePrompt = "analyze `marked-unit405-12x10-duct.pdf` through the deterministic redline-analysis lane and return its AEC intent/evidence record. Do not plan, return, or execute `/revit/*`, dry-run, apply, create, edit, delete, or write actions.\n\nAttachments:\n- [1] marked-unit405-12x10-duct.pdf (id=9b6f83e1-fd28-40ab-bc86-3036451fb67f, path=artifacts/uploads/20260711063335_marked-unit405-12x10-duct.pdf, sha256=74b03227b1e9…, bytes=863274)";
const failedLiveAttachment = [{ id: "9b6f83e1-fd28-40ab-bc86-3036451fb67f", filename: "marked-unit405-12x10-duct.pdf", relative_path: "artifacts/uploads/20260711063335_marked-unit405-12x10-duct.pdf", mime: "application/pdf" }] as any;
const step1968Prompt = "Analyze the attached PDF marked-unit405-12x10-duct.pdf using the deterministic redline-analysis lane. This is analysis only: return an AEC intent/evidence record grounded in the attachment and, if needed, the live model strictly through read-only /revit/sheets and /revit/get-titleblock-info calls only. Do NOT plan, return, or execute any other /revit/* action, including dry-run, apply, create, edit, delete, write, or any other endpoint. Do not modify the Revit model or files. Identify the redline near Unit 405 calling for a 12x10 supply duct, its likely drawing/sheet/view context, affected area/system, and confidence/ambiguities. Provide concise structured evidence with source references.\n\nAttachments:\n- [1] marked-unit405-12x10-duct.pdf (id=97a6b6b0-81bf-47bd-92e6-6ff96b6a7c30, path=artifacts/uploads/20260711100829_marked-unit405-12x10-duct.pdf, sha256=74b03227b1e9…, bytes=863274)";
const step1968Attachment = [{ id: "97a6b6b0-81bf-47bd-92e6-6ff96b6a7c30", filename: "marked-unit405-12x10-duct.pdf", relative_path: "artifacts/uploads/20260711100829_marked-unit405-12x10-duct.pdf", mime: "application/pdf" }] as any;

test("explicit read-only duct-redline analysis preflight wins over fast bridge classification", () => {
  const action = __testOnlyBuildInitialRedlinePreflightAction({ userText: readOnlyPrompt, userAttachments: attachment });
  assert.equal(__testOnlyShouldPrioritizeInitialRedlinePreflight({ userText: readOnlyPrompt, userAttachments: attachment }), true);
  assert.equal(__testOnlyIsFastElectricalPlacementRedline({ userText: readOnlyPrompt, userAttachments: attachment }), false);
  assert.equal(action?.type, "analyze_redline"); assert.equal(action?.file_path, "artifacts/uploads/duct.pdf");
  assert.equal(__testOnlyShouldPrioritizeInitialRedlinePreflight({ userText: "delete this duct", userAttachments: attachment }), false);
  assert.equal(__testOnlyShouldPrioritizeInitialRedlinePreflight({ userText: failedLivePrompt, userAttachments: failedLiveAttachment }), true);
  const failedLiveAction = __testOnlyBuildInitialRedlinePreflightAction({ userText: failedLivePrompt, userAttachments: failedLiveAttachment });
  assert.equal(failedLiveAction?.type, "analyze_redline");
  if (failedLiveAction?.type === "analyze_redline") assert.equal(failedLiveAction.file_path, failedLiveAttachment[0].relative_path);
  assert.equal(step1968Prompt.length, 894); assert.equal(__testOnlyShouldPrioritizeInitialRedlinePreflight({ userText: step1968Prompt, userAttachments: step1968Attachment }), true); assert.equal(__testOnlyBuildInitialRedlinePreflightAction({ userText: step1968Prompt, userAttachments: step1968Attachment })?.type, "analyze_redline");
  for (const prompt of ["Analyze this redline for evidence only. Do not execute other /revit/* actions, including dry run and apply.", "Interpret this redline only. Do not execute other /revit/* actions, including create, edit, delete, write, or any other endpoint.", "Analyze this redline for evidence only. Identify its likely drawing, sheet, and view context."]) assert.equal(__testOnlyShouldPrioritizeInitialRedlinePreflight({ userText: prompt, userAttachments: attachment }), true, prompt);
  for (const prompt of ["Analyze this redline only. Do not execute other /revit/* actions, including dry-run, but then delete the duct.", "Analyze this redline only. Do not execute other /revit/* actions, including apply; then replace the duct.", "Analyze this redline only. Do not execute other /revit/* actions, including write, except later edit the duct."]) assert.equal(__testOnlyShouldPrioritizeInitialRedlinePreflight({ userText: prompt, userAttachments: attachment }), false, prompt);
  for (const prompt of ["Analyze this redline for evidence only. Provide concise structured evidence by creating the marked duct.", "Analyze this redline for evidence only. Provide concise structured evidence while deleting the marked duct.", "Analyze this redline for evidence only. Do not modify the Revit model. The marked duct should be created.", "Analyze this redline for evidence only. Do not modify the Revit model, although creating a new marked duct is required.", "Analyze this redline for evidence only. Provide concise structured evidence through editing the marked duct.", "Analyze this redline for evidence only. Provide concise structured evidence via writing the duct parameters.", "Analyze this redline for evidence only. Provide concise structured evidence while moving the marked duct.", "Analyze this redline for evidence only. The work requires drawing a new duct.", "Analyze this redline for evidence only. The work requires drawing an existing duct.", "Analyze this redline for evidence only. The marked duct was deleted.", "Analyze this redline for evidence only. Do not modify the Revit model. The marked duct should be replaced."]) assert.equal(__testOnlyShouldPrioritizeInitialRedlinePreflight({ userText: prompt, userAttachments: attachment }), false, prompt);
  for (const form of ["erased", "omitted", "shifted", "rotated", "rerouted", "adjusted", "revised", "hidden", "shown", "overridden", "duplicated", "copied", "cloned", "inserted", "assigned", "drawn", "demolished"]) { const prompt = `Analyze this redline for evidence only. The marked duct should be ${form}.`; assert.equal(__testOnlyShouldPrioritizeInitialRedlinePreflight({ userText: prompt, userAttachments: attachment }), false, prompt); }
  assert.equal(__testOnlyShouldPrioritizeInitialRedlinePreflight({ userText: "Analyze this redline, then add a receptacle.", userAttachments: attachment }), false);
  assert.equal(__testOnlyShouldPrioritizeInitialRedlinePreflight({ userText: "Analyze this redline and delete the marked duct.", userAttachments: attachment }), false);
  for (const prompt of ["Analyze this redline and replace the marked duct.", "Analyze this redline and remove the marked duct.", "Analyze this redline and make the marked changes.", "Analyze this redline; do not merely summarize, create the marked duct.", "Analyze this redline without changing the model, then reroute the marked duct.", "Analyze this redline without changing the model, replace the marked duct.", "Analyze this redline; do not delete the old duct, replace it.", "Analyze this redline; do not delete, replace actions.", "Analyze this redline and relocate, swap, adjust, or revise the marked duct."]) assert.equal(__testOnlyShouldPrioritizeInitialRedlinePreflight({ userText: prompt, userAttachments: attachment }), false, prompt);
  for (const prompt of ["Analyze this redline and install the marked diffuser.", "Analyze this redline and provide the marked receptacle.", "Analyze this redline and extend the duct run.", "Analyze this redline and branch or tap the main.", "Analyze this redline and rotate or shift the tag.", "Analyze this redline and demolish or erase the note.", "Analyze this redline and tag or label the duct.", "Analyze this redline and set the parameter.", "Analyze this redline and hide or show the link.", "Analyze this redline and correct the schedule text.", "Analyze this redline and implement the markup.", "Analyze this redline and duplicate or copy the view."]) assert.equal(__testOnlyShouldPrioritizeInitialRedlinePreflight({ userText: prompt, userAttachments: attachment }), false, prompt);
  for (const prompt of ["Analyze this redline and demo the old duct.", "Analyze this redline and take out the marked duct.", "Analyze this redline and strike the note.", "Analyze this redline and x out the device.", "Analyze this redline and reorient the fixture.", "Analyze this redline and insert the receptacle.", "Analyze this redline and put the receptacle on the east wall.", "Analyze this redline and drop the receptacle into room 405.", "Analyze this redline and clone the view.", "Analyze this redline and frobnicate the marked duct.", "Analyze this redline and inspect the attachment."]) assert.equal(__testOnlyShouldPrioritizeInitialRedlinePreflight({ userText: prompt, userAttachments: attachment }), false, prompt);
  for (const prompt of ["Analyze this redline, frobnicate the duct, and return an evidence record.", "Frobnicate the duct based on this redline and return an evidence record.", "Analyze this redline for an evidence record, then frobnicate the duct.", "Analyze this redline and return an evidence record; frobnicate duct A."]) assert.equal(__testOnlyShouldPrioritizeInitialRedlinePreflight({ userText: prompt, userAttachments: attachment }), false, prompt);
  for (const prompt of ["Analyze this redline and frobnicate duct A only.", "Analyze this redline and frobnicate duct A; return a read-only response."]) assert.equal(__testOnlyShouldPrioritizeInitialRedlinePreflight({ userText: prompt, userAttachments: attachment }), false, prompt);
});

test("exact failed-live request uses the production read-only decision lane once and discards returned actions", async () => {
  const order: string[] = []; let summaries = 0, fastCalls = 0;
  const lane = await __testOnlyRunInitialRedlineDecisionLane({
    userText: failedLivePrompt, userAttachments: failedLiveAttachment,
    runInitialPreflight: async (action) => { order.push(action.type); },
    runFastPreflight: async () => { fastCalls += 1; order.push("fast"); return null; },
    summarize: async () => { summaries += 1; order.push("summary"); return { assistant_message: "Grounded deterministic evidence summary.", actions: [{ action_id: "write", method: "POST", path: "/revit/delete", body_json: "{}" }], workbench_actions: [{ type: "shell", command: "should-not-run" }], dev_actions: [{ type: "restart_backend" }], web_requests: [{ request_id: "web", url: "https://example.invalid", purpose: "should-not-run" }] } as any; }
  });
  assert.deepEqual(order, ["analyze_redline", "summary"]); assert.equal(summaries, 1); assert.equal(fastCalls, 0); assert.equal(lane.fastPreflight, null);
  assert.deepEqual(lane.response, { version: "operator.backend.v1", assistant_message: "Grounded deterministic evidence summary.", actions: [] }); assert.equal(JSON.stringify(lane.response).includes("should-not-run"), false); assert.equal(JSON.stringify(lane.response).includes("/revit/delete"), false);
});

test("authoritative step 1968 safety list keeps both dispatches on one analysis-only lane", async () => {
  const req = { version: "operator.backend.v1", session_id: "ff088c6a-359c-4d15-97ff-7894e1d3415c", message_id: "f053cd9f-2b13-4389-b455-434f65f0f000", user_text: step1968Prompt, user_attachments: step1968Attachment } as any;
  const action = __testOnlyBuildInitialRedlinePreflightAction({ userText: step1968Prompt, userAttachments: step1968Attachment }); assert.equal(action?.type, "analyze_redline"); if (action?.type === "analyze_redline") assert.equal(action.file_path, step1968Attachment[0].relative_path);
  for (const dispatch of ["non-streaming", "streaming"]) { let resolverCalls = 0; const response = await __testOnlyMaybeRunTopLevelMepRouteRedline(req, async () => { resolverCalls += 1; return { version: "operator.backend.v1", assistant_message: "resolver", actions: [] }; }); assert.equal(response, null, dispatch); assert.equal(resolverCalls, 0, dispatch); }
  const order: string[] = []; const lane = await __testOnlyRunInitialRedlineDecisionLane({ userText: step1968Prompt, userAttachments: step1968Attachment, runInitialPreflight: async (entry) => { order.push(entry.type); }, runFastPreflight: async () => { order.push("fast"); return null; }, summarize: async () => { order.push("summary"); return { assistant_message: "Evidence summary", actions: [{ action_id: "unexpected", method: "POST", path: "/revit/delete", body_json: "{}" }] } as any; } });
  assert.deepEqual(order, ["analyze_redline", "summary"]); assert.equal(lane.fastPreflight, null); assert.deepEqual(lane.response, { version: "operator.backend.v1", assistant_message: "Evidence summary", actions: [] });
});

test("top-level MEP routing bypass is structured-attachment-only and shared by dispatch modes", async () => {
  assert.equal(failedLivePrompt.length, 427);
  const req = { version: "operator.backend.v1", session_id: "01c787ea-1580-4ccc-9c15-94cbb0568d75", message_id: "6c48bfc5-d3e9-4605-acf2-53254af3ed5c", user_text: failedLivePrompt, user_attachments: failedLiveAttachment } as any;
  let resolverCalls = 0, coordinatorCalls = 0;
  const resolver = async () => { resolverCalls += 1; return { version: "operator.backend.v1", assistant_message: "resolver", actions: [] }; };
  const routed = await __testOnlyMaybeRunTopLevelMepRouteRedline(req, resolver as any);
  const coordinator = async () => { coordinatorCalls += 1; return { version: "operator.backend.v1", assistant_message: "Evidence summary", actions: [] }; };
  const response = routed ?? await coordinator();
  assert.equal(resolverCalls, 0); assert.equal(coordinatorCalls, 1); assert.deepEqual(response, { version: "operator.backend.v1", assistant_message: "Evidence summary", actions: [] });
  for (const variant of [{ ...req, user_text: "Delete this marked duct from the redline." }, { ...req, user_attachments: undefined }, { ...req, user_text: "Analyze this redline attachment." }]) { resolverCalls = 0; await __testOnlyMaybeRunTopLevelMepRouteRedline(variant, resolver as any); assert.equal(resolverCalls, 1); }
});

test("workbench analyze_redline appends only deterministic evidence and preserves legacy details", async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "redline-live-gap-")), previousRoot = process.env.OPERATOR_WORKSPACE_ROOT, relative = "artifacts/uploads/duct.pdf", file = path.join(root, relative);
  fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, buildCommentedPdf(1, new Map([[1, "12x10 SA duct 450 CFM"]]))); process.env.OPERATOR_WORKSPACE_ROOT = root;
  try {
    const actions = [{ type: "analyze_redline", file_path: relative, include_pdf_annotations: true }] as const;
    const [result] = await executeWorkbenchActions(actions as any); const details: any = result?.details, evidence = details?.aec_intent_evidence;
    assert.equal(result?.ok, true); assert.equal(details?.file_path, relative); assert.equal(details?.request?.file_path, relative); assert.equal(evidence?.evidence[0]?.sha256, createHash("sha256").update(fs.readFileSync(file)).digest("hex"));
    const annotation = evidence.evidence.find((item: any) => item.kind === "pdf_annotation"); assert.equal(annotation.page.number, 1); assert.deepEqual(annotation.page.normalized_box, { min_x: annotation.page.normalized_box.min_x, min_y: annotation.page.normalized_box.min_y, max_x: annotation.page.normalized_box.max_x, max_y: annotation.page.normalized_box.max_y }); assert.equal(annotation.frame.coordinate_frame, "pdf-page-1-normalized");
    assert.equal(evidence.target.status, "ambiguous"); assert.deepEqual(evidence.intent.proposed_actions.map((item: any) => item.tool), ["/revit/sheets", "/revit/get-titleblock-info"]); assert.ok(evidence.intent.proposed_actions.every((item: any) => item.requires_apply === false)); assert.ok(evidence.verification.observed.every((item: any) => item.status === "not_run")); assert.equal(result?.type, "analyze_redline");
    const [hashFailure] = await executeWorkbenchActions(actions as any, { createRedlineAnalyzeEvidence: async () => { throw new Error("simulated post-analysis hash race"); } }); assert.equal(hashFailure?.ok, true); assert.equal((hashFailure?.details as any)?.aec_intent_evidence, undefined);
    const legacyProjection = (value: any) => { const copy = JSON.parse(JSON.stringify(value)); delete copy?.details?.aec_intent_evidence; delete copy?.details?.vision_artifacts; return copy; };
    assert.deepEqual(legacyProjection(result), legacyProjection(hashFailure));
    const [failed] = await executeWorkbenchActions([{ type: "analyze_redline", file_path: "missing.pdf" }]); assert.equal(failed?.ok, false); assert.equal((failed?.details as any)?.aec_intent_evidence, undefined);
  } finally { if (previousRoot === undefined) delete process.env.OPERATOR_WORKSPACE_ROOT; else process.env.OPERATOR_WORKSPACE_ROOT = previousRoot; fs.rmSync(root, { recursive: true, force: true }); }
});

test("initial analysis grounding performs the two declared reads once and exposes only grounded evidence", async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "redline-grounding-runtime-")), previousRoot = process.env.OPERATOR_WORKSPACE_ROOT, relative = "artifacts/uploads/marked-unit405.pdf", file = path.join(root, relative);
  fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, Buffer.from(buildCommentedPdf(1, new Map([[1, "M104 12x10 SA duct 450 CFM"]])).toString("binary").replace("A-001", "M104 "), "binary")); process.env.OPERATOR_WORKSPACE_ROOT = root;
  try {
    const [analyzed] = await executeWorkbenchActions([{ type: "analyze_redline", file_path: relative, include_pdf_annotations: true }] as any), calls: any[] = [], input = analyzed!, evidence: any = structuredClone((input as any)?.details?.aec_intent_evidence);
    assert.equal(evidence.target.sheet?.number, "M104"); assert.deepEqual(evidence.intent.proposed_actions, [{ tool: "/revit/sheets", requires_apply: false, body: { action: "detail", sheetNumber: "M104", includePlacedViews: true, includeViewports: true, includeViewportGeometry: true, includeTitleBlocks: true, includeSheetOutline: true } }, { tool: "/revit/get-titleblock-info", requires_apply: false, body: { sheetNumber: "M104" } }]);
    const grounded = await groundInitialRedlineWorkbenchResults("grounding-session", [input], { createActionId: (() => { let n = 0; return () => `a-${++n}`; })(), callBridge: async (_session, method, path, body) => { calls.push({ method, path, body }); return path === "/revit/sheets" ? { ok: true, method, path, result_json: { status: "Ok", action: "detail", sheetElementId: 104, sheetId: 104, viewId: 104, sheetNumber: "M104", sheetName: "HVAC", isPlaceholder: false, titleBlockCount: 1, titleBlocks: [{ elementId: 901, typeId: 77 }], placedViewCount: 1, placedViews: [{ viewId: 501, name: "HVAC PLAN", viewType: "EngineeringPlan", scale: 100, viewportIds: [1] }] } } : { ok: true, method, path, result_json: { ok: true, sheetId: 104, sheetViewId: 104, sheetNumber: "M104", titleblockInstanceId: 901, titleblockTypeId: 77, titleblockCount: 1 } }; } });
    const groundedEvidence: any = grounded[0]?.details?.aec_intent_evidence;
    assert.deepEqual(calls, [{ method: "POST", path: "/revit/sheets", body: { action: "detail", sheetNumber: "M104", includePlacedViews: true, includeViewports: true, includeViewportGeometry: true, includeTitleBlocks: true, includeSheetOutline: true } }, { method: "POST", path: "/revit/get-titleblock-info", body: { sheetNumber: "M104" } }]); assert.deepEqual(groundedEvidence.target.sheet, { number: "M104", id: 104 }); assert.deepEqual(groundedEvidence.target.view, { id: 501, name: "HVAC PLAN" }); assert.equal(JSON.stringify(grounded).includes("result_json"), false); assert.notEqual(groundedEvidence, evidence); assert.deepEqual((input as any).details.aec_intent_evidence, evidence); const legacyOutput: any = structuredClone(grounded[0]); const legacyInput: any = structuredClone(input); delete legacyOutput.details.aec_intent_evidence; delete legacyInput.details.aec_intent_evidence; assert.deepEqual(legacyOutput, legacyInput);
    const failed = await groundInitialRedlineWorkbenchResults("grounding-session", [input], { callBridge: async (_s, m, p) => ({ ok: false, method: m, path: p }) }); assert.deepEqual(failed, [input]);
    const rejectedEvidence = adaptRedlineAnalyzeToAecIntentEvidence({ file_path: relative, likely_sheet: true, primary_sheet_number: "M104", pages: [{ page: 1, text_excerpt: "M104", text_chars: 4, sheet_candidates: [] }], pdf_annotations: [], route_candidates: [], suggested_revit_calls: [{ method: "POST", path: "/revit/sheets", body: new Proxy({ action: "detail", sheetNumber: "M104", includePlacedViews: true, includeViewports: true, includeViewportGeometry: true, includeTitleBlocks: true }, {}) }, { method: "POST", path: "/revit/get-titleblock-info", body: { sheetNumber: "M104" } }] } as any, { id: "rejected-sheet", created_at: "2026-07-11T00:00:00.000Z", sha256: (input as any).details.aec_intent_evidence.target.document.fingerprint }); const rejectedInput = { ...input, details: { ...(input as any).details, aec_intent_evidence: rejectedEvidence } }; let rejectedCalls = 0; assert.deepEqual(await groundInitialRedlineWorkbenchResults("grounding-session", [rejectedInput], { callBridge: async () => { rejectedCalls += 1; throw new Error("rejected adapter body must not call"); } }), [rejectedInput]); assert.equal(rejectedCalls, 0);
    for (const mutate of [(v: any) => { v.details.aec_intent_evidence.intent.domain = "mep"; }, (v: any) => { delete v.details.aec_intent_evidence.target.document.fingerprint; }, (v: any) => { v.details.aec_intent_evidence.target.document.fingerprint = "b".repeat(64); }, (v: any) => { v.details.aec_intent_evidence.intent.proposed_actions[0].body.apply = true; }, (v: any) => { v.details.aec_intent_evidence.intent.proposed_actions.pop(); }]) { const bad = structuredClone(input); mutate(bad); let count = 0; assert.deepEqual(await groundInitialRedlineWorkbenchResults("grounding-session", [bad], { callBridge: async () => { count += 1; throw new Error("must not call"); } }), [bad]); assert.equal(count, 0); }
  } finally { if (previousRoot === undefined) delete process.env.OPERATOR_WORKSPACE_ROOT; else process.env.OPERATOR_WORKSPACE_ROOT = previousRoot; fs.rmSync(root, { recursive: true, force: true }); }
});

test("initial grounding fails closed before and during every adversarial bridge boundary", async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "redline-grounding-adversarial-")), previousRoot = process.env.OPERATOR_WORKSPACE_ROOT, relative = "artifacts/uploads/marked-unit405.pdf", file = path.join(root, relative);
  fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, Buffer.from(buildCommentedPdf(1, new Map([[1, "M104 duct"]])).toString("binary").replace("A-001", "M104 "), "binary")); process.env.OPERATOR_WORKSPACE_ROOT = root;
  try {
    const [analyzed] = await executeWorkbenchActions([{ type: "analyze_redline", file_path: relative }] as any), base: any = analyzed!, unchanged = async (value: any, deps: any) => assert.deepEqual(await groundInitialRedlineWorkbenchResults("adversarial", [value], deps), [value]);
    const invalid: Array<[string, (value: any) => void]> = [["wrong action", v => v.details.aec_intent_evidence.intent.action = "other"], ["wrong status", v => v.details.aec_intent_evidence.target.status = "resolved"], ["duplicate proposal", v => v.details.aec_intent_evidence.intent.proposed_actions.push(structuredClone(v.details.aec_intent_evidence.intent.proposed_actions[1]))], ["missing sheet field", v => delete v.details.aec_intent_evidence.intent.proposed_actions[0].body.includeSheetOutline], ["false sheet field", v => v.details.aec_intent_evidence.intent.proposed_actions[0].body.includeTitleBlocks = false], ["mismatched sheet field", v => v.details.aec_intent_evidence.intent.proposed_actions[0].body.sheetNumber = "M105"], ["malformed sheet field", v => v.details.aec_intent_evidence.intent.proposed_actions[0].body.includeViewports = "true"], ["dry run", v => v.details.aec_intent_evidence.intent.proposed_actions[0].body.dry_run = true], ["write", v => v.details.aec_intent_evidence.intent.proposed_actions[0].body.write = true], ["extra", v => v.details.aec_intent_evidence.intent.proposed_actions[0].body.extra = true], ["missing fingerprint", v => delete v.details.aec_intent_evidence.target.document.fingerprint], ["malformed fingerprint", v => v.details.aec_intent_evidence.target.document.fingerprint = "not-a-sha"], ["mismatched fingerprint", v => v.details.aec_intent_evidence.target.document.fingerprint = "b".repeat(64)], ["conflicting fingerprint", v => v.details.aec_intent_evidence.evidence.push({ ...structuredClone(v.details.aec_intent_evidence.evidence[0]), id: "conflict", sha256: "b".repeat(64) })]];
    for (const [name, mutate] of invalid) { const value = structuredClone(base); mutate(value); let calls = 0; await unchanged(value, { callBridge: async () => { calls++; throw new Error(name); } }); assert.equal(calls, 0, name); }
    for (const ids of [["", "b"], ["x".repeat(513), "b"], ["same", "same"]]) { let calls = 0, index = 0; await unchanged(structuredClone(base), { createActionId: () => ids[index++]!, callBridge: async () => { calls++; throw new Error("no call"); } }); assert.equal(calls, 0); }
    { let calls = 0; await assert.rejects(() => groundInitialRedlineWorkbenchResults("adversarial", [structuredClone(base)], { createActionId: () => { throw new Error("id failure"); }, callBridge: async () => { calls++; throw new Error("no call"); } }), /id failure/); assert.equal(calls, 0, "throwing createActionId must not start a bridge call"); }
    const success = (method: "POST", path: string) => path === "/revit/sheets" ? { ok: true, method, path, result_json: { status: "Ok", action: "detail", sheetElementId: 104, sheetId: 104, viewId: 104, sheetNumber: "M104", sheetName: "HVAC", isPlaceholder: false, titleBlockCount: 1, titleBlocks: [{ elementId: 901, typeId: 77 }], placedViewCount: 1, placedViews: [{ viewId: 501, name: "HVAC", viewType: "EngineeringPlan", scale: 100, viewportIds: [1] }] } } : { ok: true, method, path, result_json: { ok: true, sheetId: 104, sheetViewId: 104, sheetNumber: "M104", titleblockInstanceId: 901, titleblockTypeId: 77, titleblockCount: 1 } };
    for (const mode of ["firstFalse", "firstThrow", "secondFalse", "secondThrow", "methodMismatch", "pathMismatch", "malformed", "notFound", "lowercaseStatus", "extraStatus", "extraAction", "sheetMismatch", "multipleTitleblocks"] as const) { let calls = 0; await unchanged(structuredClone(base), { callBridge: async (_s: string, method: "POST", path: any) => { calls++; if (mode === "firstThrow" && calls === 1 || mode === "secondThrow" && calls === 2) throw new Error(mode); if (mode === "firstFalse" && calls === 1 || mode === "secondFalse" && calls === 2) return { ok: false, method, path }; if (mode === "methodMismatch" && calls === 1) return { ...success(method, path), method: "GET" }; if (mode === "pathMismatch" && calls === 1) return { ...success(method, path), path: "/revit/other" }; if (mode === "malformed" && calls === 1) return { ok: true, method, path, result_json: null }; const result: any = success(method, path); if (calls === 1 && mode === "notFound") result.result_json.status = "NotFound"; if (calls === 1 && mode === "lowercaseStatus") result.result_json.status = "ok"; if (calls === 1 && mode === "extraStatus") result.result_json.status = "Ok "; if (calls === 1 && mode === "extraAction") result.result_json.action = "detail "; if (calls === 1 && mode === "sheetMismatch") result.result_json.sheetId = 105; if (calls === 1 && mode === "multipleTitleblocks") { result.result_json.titleBlockCount = 2; result.result_json.titleBlocks.push({ elementId: 902, typeId: 78 }); } return result; } }); assert.equal(calls, mode.startsWith("second") ? 2 : 1, mode); }
  } finally { if (previousRoot === undefined) delete process.env.OPERATOR_WORKSPACE_ROOT; else process.env.OPERATOR_WORKSPACE_ROOT = previousRoot; fs.rmSync(root, { recursive: true, force: true }); }
});

test("initial grounding snapshots untrusted bridge results before probing consumer eligibility", async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "redline-grounding-snapshot-")), previousRoot = process.env.OPERATOR_WORKSPACE_ROOT, relative = "artifacts/uploads/marked-unit405.pdf", file = path.join(root, relative);
  fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, Buffer.from(buildCommentedPdf(1, new Map([[1, "M104 duct"]])).toString("binary").replace("A-001", "M104 "), "binary")); process.env.OPERATOR_WORKSPACE_ROOT = root;
  try {
    const [analyzed] = await executeWorkbenchActions([{ type: "analyze_redline", file_path: relative }] as any), base: any = analyzed!;
    const view = (id = 501, extra: any = {}) => ({ viewId: id, name: "HVAC", viewType: "EngineeringPlan", scale: 100, viewportIds: [1], ...extra });
    const sheet = () => ({ status: "Ok", action: "detail", sheetElementId: 104, sheetId: 104, viewId: 104, sheetNumber: "M104", sheetName: "HVAC", isPlaceholder: false, titleBlockCount: 1, titleBlocks: [{ elementId: 901, typeId: 77 }], placedViewCount: 1, placedViews: [view()] });
    const title = () => ({ ok: true, sheetId: 104, sheetViewId: 104, sheetNumber: "M104", titleblockInstanceId: 901, titleblockTypeId: 77, titleblockCount: 1 });
    const response = (result_json: any) => ({ ok: true, method: "POST" as const, path: "/revit/sheets", result_json });
    const unchanged = async (first: any, expectedCalls = 1) => { let calls = 0; const output = await groundInitialRedlineWorkbenchResults("snapshot", [base], { createActionId: (() => { let n = 0; return () => `s-${++n}`; })(), callBridge: async (_s, method, path) => { calls++; return calls === 1 ? first : { ok: true, method, path, result_json: title() }; } }); assert.equal(calls, expectedCalls); assert.deepEqual(output, [base]); };
    for (const mutate of [(value: any) => { value.placedViews = []; value.placedViewCount = 0; }, (value: any) => { value.placedViews = [{ viewId: 501 }]; }, (value: any) => { value.placedViews = [view(), view(502)]; value.placedViewCount = 2; }, (value: any) => { value.placedViews = [view(), view(501, { scale: 50 })]; value.placedViewCount = 2; }]) { const value = sheet(); mutate(value); await unchanged(response(value)); }
    { const value = sheet(); value.placedViews = [view(), structuredClone(value.placedViews[0])]; value.placedViewCount = 2; let calls = 0; const output: any = await groundInitialRedlineWorkbenchResults("snapshot", [base], { createActionId: (() => { let n = 0; return () => `d-${++n}`; })(), callBridge: async (_s, method, path) => { calls++; return calls === 1 ? response(value) : { ok: true, method, path, result_json: title() }; } }); assert.equal(calls, 2); assert.equal(output[0].details.aec_intent_evidence.target.view.id, 501); }
    { const key = "k".repeat(AEC_INTENT_EVIDENCE_MAX_STRING_CHARS), raw: any = response(sheet()); raw[key] = null; let calls = 0; const output: any = await groundInitialRedlineWorkbenchResults("snapshot", [base], { createActionId: (() => { let n = 0; return () => `k-${++n}`; })(), callBridge: async (_s, method, path) => { calls++; return calls === 1 ? raw : { ok: true, method, path, result_json: title() }; } }); assert.equal(calls, 2); assert.equal(output[0].details.aec_intent_evidence.target.view.id, 501); }
    for (const add of [(raw: any, key: string) => raw[key] = null, (raw: any, key: string) => raw.result_json[key] = null, (raw: any, key: string) => raw.result_json.placedViews[0][key] = null, (raw: any, key: string) => raw.result_json.titleBlocks[0][key] = null]) { const raw: any = response(sheet()); await assert.doesNotReject(() => unchanged((add(raw, "k".repeat(AEC_INTENT_EVIDENCE_MAX_STRING_CHARS + 1)), raw))); }
    const unsafe: Array<[string, () => any, () => number]> = [];
    const countedGetter = (target: any, key: string) => { let count = 0; Object.defineProperty(target, key, { enumerable: true, get() { count++; return true; } }); return () => count; };
    { const raw = response(sheet()); unsafe.push(["root getter", () => raw, countedGetter(raw, "ok")]); }
    { const raw = response(sheet()); unsafe.push(["result getter", () => raw, countedGetter(raw.result_json, "status")]); }
    { const raw = response(sheet()); unsafe.push(["placed-views getter", () => raw, countedGetter(raw.result_json, "placedViews")]); }
    { const raw = response(sheet()); unsafe.push(["array getter", () => raw, countedGetter(raw.result_json.placedViews, "0")]); }
    { const raw = response(sheet()); unsafe.push(["entry getter", () => raw, countedGetter(raw.result_json.placedViews[0], "name")]); }
    { const raw = response(sheet()); unsafe.push(["titleblock getter", () => raw, countedGetter(raw.result_json.titleBlocks[0], "elementId")]); }
    for (const [name, make] of [["root class", () => Object.assign(new (class {})(), response(sheet()))], ["root null prototype", () => Object.assign(Object.create(null), response(sheet()))], ["root proxy", () => new Proxy(response(sheet()), {})], ["root throwing proxy", () => new Proxy({}, { ownKeys() { throw new Error("trap"); } })], ["result class", () => response(Object.assign(new (class {})(), sheet()))], ["result null prototype", () => response(Object.assign(Object.create(null), sheet()))], ["result proxy", () => response(new Proxy(sheet(), {}))], ["array proxy", () => { const value = sheet(); value.placedViews = new Proxy(value.placedViews, {}); return response(value); }], ["entry class", () => { const value = sheet(); value.placedViews = [Object.assign(new (class {})(), view())]; return response(value); }], ["titleblock null prototype", () => { const value = sheet(); value.titleBlocks = [Object.assign(Object.create(null), value.titleBlocks[0])]; return response(value); }], ["symbol", () => { const raw: any = response(sheet()); raw[Symbol("x")] = 1; return raw; }], ["nonenumerable", () => { const raw: any = response(sheet()); Object.defineProperty(raw, "hidden", { value: 1 }); return raw; }]] as Array<[string, () => any]>) unsafe.push([name, make, () => 0]);
    for (const [name, make, getterCount] of unsafe) { await assert.doesNotReject(() => unchanged(make())); assert.equal(getterCount(), 0, name); }
    for (const mutate of [(value: any) => { value.self = value; }, (value: any) => { let cursor = value; for (let i = 0; i < 34; i++) cursor = cursor.deep = {}; }, (value: any) => { value.items = Array.from({ length: 1_001 }, () => 1); }, (value: any) => { value.placedViews[0].scale = Infinity; }, (value: any) => { value.placedViews = [view(), ,]; }]) { const value = sheet(); mutate(value); await unchanged(response(value)); }
    { const raw: any = response(sheet()); let calls = 0; const output: any = await groundInitialRedlineWorkbenchResults("snapshot", [base], { createActionId: (() => { let n = 0; return () => `m-${++n}`; })(), callBridge: async (_s, method, path) => { calls++; if (calls === 1) return raw; raw.result_json.placedViews[0].name = "MUTATED"; return { ok: true, method, path, result_json: title() }; } }); assert.equal(calls, 2); assert.equal(output[0].details.aec_intent_evidence.target.view.name, "HVAC"); assert.equal(JSON.stringify(output).includes("result_json"), false); }
    let calls = 0; const malformedSecond: any = await groundInitialRedlineWorkbenchResults("snapshot", [base], { createActionId: (() => { let n = 0; return () => `x-${++n}`; })(), callBridge: async (_s, method, path) => { calls++; return calls === 1 ? response(sheet()) : { ok: true, method, path, result_json: Object.assign(new (class {})(), title()) }; } }); assert.equal(calls, 2); assert.deepEqual(malformedSecond, [base]);
  } finally { if (previousRoot === undefined) delete process.env.OPERATOR_WORKSPACE_ROOT; else process.env.OPERATOR_WORKSPACE_ROOT = previousRoot; fs.rmSync(root, { recursive: true, force: true }); }
});
