import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const source = fs.readFileSync(path.join(root, 'contracts/supported-tool-inventory.v1.json'), 'utf8').replaceAll('\r\n', '\n');
const inventory = JSON.parse(source);
if (inventory.schema !== 'revit-operator.supported-tool-inventory.v1') throw new Error('Unsupported tool inventory schema.');
const hash = 'sha256:' + createHash('sha256').update(source).digest('hex');
function keys(rows) {
  const result = rows.map(row => {
    if (!['GET', 'POST'].includes(row.method) || !/^\/revit\/[a-z0-9_/-]+$/.test(row.path)) throw new Error('Noncanonical inventory route.');
    return `${row.method} ${row.path}`;
  }).sort();
  if (new Set(result).size !== result.length) throw new Error('Duplicate inventory route.');
  return result;
}
const native = keys(inventory.native_routes), internal = keys(inventory.internal_routes), standalone = keys(inventory.standalone_routes);
const aliases = [...inventory.mcp_aliases].sort();
if (new Set([...native, ...internal, ...standalone]).size !== native.length + internal.length + standalone.length) throw new Error('Overlapping executor inventory.');
if (new Set(aliases).size !== aliases.length) throw new Error('Duplicate MCP alias.');
const ts = `// Generated by scripts/generate_supported_tool_inventory.mjs. Edit the shared inventory, not this file.
export const SUPPORTED_TOOL_INVENTORY_HASH = ${JSON.stringify(hash)};
export const SUPPORTED_NATIVE_ROUTES: readonly string[] = Object.freeze(${JSON.stringify(native, null, 2)});
export const SUPPORTED_INTERNAL_ROUTES: readonly string[] = Object.freeze(${JSON.stringify(internal, null, 2)});
export const SUPPORTED_STANDALONE_ROUTES: readonly string[] = Object.freeze(${JSON.stringify(standalone, null, 2)});
export const SUPPORTED_MCP_ALIASES: readonly string[] = Object.freeze(${JSON.stringify(aliases, null, 2)});
const native = new Set(SUPPORTED_NATIVE_ROUTES), internal = new Set(SUPPORTED_INTERNAL_ROUTES);
const standalone = new Set(SUPPORTED_STANDALONE_ROUTES), aliases = new Set(SUPPORTED_MCP_ALIASES);
export function isSupportedNativeTool(method: string, path: string): boolean { return native.has(method + ' ' + path); }
export function isSupportedToolRoute(method: string, path: string): boolean { return isSupportedNativeTool(method, path) || standalone.has(method + ' ' + path); }
export function isSupportedNativeTransport(method: string, path: string): boolean { return isSupportedNativeTool(method, path) || internal.has(method + ' ' + path); }
export function isSupportedMcpAlias(alias: string): boolean { return aliases.has(alias); }
export class UnsupportedProductToolError extends Error {
  readonly code = 'PRODUCT_TOOL_NOT_SUPPORTED'; readonly phase = 'pre_dispatch';
  readonly retryable = false; readonly outcomeUnknown = false; readonly requestDispatched = false;
  constructor(method: string, path: string) { super('This tool is outside the supported product inventory: ' + method + ' ' + path); }
}
export function requireSupportedToolRoute(method: string, path: string): void { if (!isSupportedToolRoute(method, path)) throw new UnsupportedProductToolError(method, path); }
export function requireSupportedNativeTransport(method: string, path: string): void { if (!isSupportedNativeTransport(method, path)) throw new UnsupportedProductToolError(method, path); }
`;
const csSet = (name, values) => `        private static readonly HashSet<string> ${name} = new HashSet<string>(StringComparer.Ordinal)\n        {\n${values.map(v => '            ' + JSON.stringify(v) + ',').join('\n')}\n        };\n`;
const cs = `// Generated by scripts/generate_supported_tool_inventory.mjs. Edit the shared inventory, not this file.
using System;
using System.Collections.Generic;
namespace RevitBridge.Common
{
    public static class OperatorSupportedToolInventory
    {
        public const string InventoryHash = ${JSON.stringify(hash)};
${csSet('Native', native)}${csSet('Internal', internal)}        public static bool IsSupportedTool(string method, string path) => Native.Contains(method + " " + path);
        public static bool IsSupportedTransport(string method, string path) => IsSupportedTool(method, path) || Internal.Contains(method + " " + path);
        public static void RequireSupportedTool(string method, string path)
        {
            if (!IsSupportedTool(method, path)) throw new OperatorToolUserErrorException("This tool is outside the supported product inventory: " + method + " " + path, "PRODUCT_TOOL_NOT_SUPPORTED");
        }
        public static void RequireSupportedTransport(string method, string path)
        {
            if (!IsSupportedTransport(method, path)) throw new OperatorToolUserErrorException("This route is outside the native host product inventory: " + method + " " + path, "PRODUCT_TOOL_NOT_SUPPORTED");
        }
    }
}
`;
const outputs = new Map([
  ['apps/mcp-server/src/lib/supportedToolInventory.ts', ts],
  ['apps/operator-backend/src/capabilities/supported_tool_inventory.ts', ts],
  ['apps/revit-bridge-addin/RevitBridge.Common/OperatorSupportedToolInventory.cs', cs]
]);
for (const [relative, content] of outputs) {
  const target = path.join(root, fs.existsSync(path.join(root, "apps/operator-backend")) ? relative : relative.replace(/^apps\//, ""));
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8').replaceAll('\r\n', '\n') !== content) throw new Error(`Stale supported inventory projection: ${relative}`);
  } else fs.writeFileSync(target, content);
}
console.log(JSON.stringify({ hash, native: native.length, mcp: aliases.length, internal: internal.length, standalone: standalone.length }));
